// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QHIcBSqPp2hOKml2dIwA7O971CzPDrs',
    appId: '1:790979539420:web:b76367f4fec049fdf25f19',
    messagingSenderId: '790979539420',
    projectId: 'xelpcom-338b9',
    authDomain: 'xelpcom-338b9.firebaseapp.com',
    storageBucket: 'xelpcom-338b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwRGRpX5RXPGcq1jZltw145morpV2Gb78',
    appId: '1:790979539420:android:0522f038bf4270c8f25f19',
    messagingSenderId: '790979539420',
    projectId: 'xelpcom-338b9',
    storageBucket: 'xelpcom-338b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxkmmvX-PCFlrNEaWilFB-9vi9UC7_PVg',
    appId: '1:790979539420:ios:db493a3c88b12a94f25f19',
    messagingSenderId: '790979539420',
    projectId: 'xelpcom-338b9',
    storageBucket: 'xelpcom-338b9.appspot.com',
    iosClientId: '790979539420-hb5lqsr5hcve62dn9s93a5d03in0dflu.apps.googleusercontent.com',
    iosBundleId: 'com.example.xelpcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxkmmvX-PCFlrNEaWilFB-9vi9UC7_PVg',
    appId: '1:790979539420:ios:db493a3c88b12a94f25f19',
    messagingSenderId: '790979539420',
    projectId: 'xelpcom-338b9',
    storageBucket: 'xelpcom-338b9.appspot.com',
    iosClientId: '790979539420-hb5lqsr5hcve62dn9s93a5d03in0dflu.apps.googleusercontent.com',
    iosBundleId: 'com.example.xelpcom',
  );
}
